/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface EsnAppGrid {
    /**
     * A serialized JSON object that contains information about the available apps.
     */
    serializedItems: string;
  }
  interface EsnPopover {
    /**
     * A method to toggle the popover on/off.
     */
    toggleShowState: () => Promise<void>;
  }
  interface MyComponent {
    /**
     * The first name
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     */
    middle: string;
  }
}
declare global {
  interface HTMLEsnAppGridElement extends Components.EsnAppGrid, HTMLStencilElement {}
  var HTMLEsnAppGridElement: {
    prototype: HTMLEsnAppGridElement;
    new (): HTMLEsnAppGridElement;
  };
  interface HTMLEsnPopoverElement extends Components.EsnPopover, HTMLStencilElement {}
  var HTMLEsnPopoverElement: {
    prototype: HTMLEsnPopoverElement;
    new (): HTMLEsnPopoverElement;
  };
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'esn-app-grid': HTMLEsnAppGridElement;
    'esn-popover': HTMLEsnPopoverElement;
    'my-component': HTMLMyComponentElement;
  }
}
declare namespace LocalJSX {
  interface EsnAppGrid {
    /**
     * A serialized JSON object that contains information about the available apps.
     */
    serializedItems?: string;
  }
  interface EsnPopover {}
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }
  interface IntrinsicElements {
    'esn-app-grid': EsnAppGrid;
    'esn-popover': EsnPopover;
    'my-component': MyComponent;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'esn-app-grid': LocalJSX.EsnAppGrid & JSXBase.HTMLAttributes<HTMLEsnAppGridElement>;
      'esn-popover': LocalJSX.EsnPopover & JSXBase.HTMLAttributes<HTMLEsnPopoverElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}
